Repository Hiviexd/AxerBot, pull requests merged in 2022-11, with the labels that each got.

#215 Support `BSC` in usergroup detection
  commands/BNsite/bn.ts
  commands/user/mapper.ts
  commands/user/mapsetrank.ts
  commands/user/player.ts
  commands/user/recent.ts
  helpers/osu/player/getHighestUsergroup.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
Labels: size/L

#216 A couple requests from the osu!catch modding hub
  commands/management/subcommands/verification/setButton.ts
  commands/management/verification.ts
  database/index.ts
  database/migrations/addButtonToGuildVerification.ts
  database/schemas/guild.ts
  modules/loggers/logMessageDelete.ts
  modules/loggers/logMessageEdit.ts
  modules/loggers/logServerJoins.ts
  modules/loggers/logServerLeaves.ts
  modules/verification/client/StartVerification.ts
Labels: size/L

#217 Add bsc to verification
  commands/management/subcommands/verification/removeGroupRole.ts
  commands/management/verification.ts
Labels: size/M

#218 rewrite logging to slash
  commands/management/logging.ts
  commands/management/subcommands/logging/disable.ts
  commands/management/subcommands/logging/enable.ts
  commands/management/verification.ts
  modules/loggers/logMessageDelete.ts
  modules/loggers/logMessageEdit.ts
  modules/loggers/logServerJoins.ts
  modules/loggers/logServerLeaves.ts
  responses/qat/BNEmbed.ts
Labels: size/L

#219 add user logging + more stats to mapper/bn embed
  commands/index.ts
  commands/management/subcommands/logging/disable.ts
  commands/management/subcommands/logging/enable.ts
  commands/management/subcommands/userLog/add.ts
  commands/management/subcommands/userLog/remove.ts
  commands/management/userLog.ts
  database/schemas/guild.ts
  helpers/qat/getters/resets/parseResets.ts
  responses/osu/MapperEmbed.ts
  responses/qat/BNEmbed.ts
  types/user.ts
Labels: size/L

#220 userlog permission hotfix
  commands/management/userLog.ts
Labels: size/XS

#221 fix inaccuracy of total maps count
  responses/osu/MapperEmbed.ts
Labels: size/S

#222 Fix error handling in reminders module
  helpers/core/logger.ts
  modules/reminders/remindersChecker.ts
Labels: size/L
