Repository Hiviexd/AxerBot, pull requests merged in 2022-03, with the labels that each got.

#8 Refactory mapper.js and fix some things
  .prettierrc
  commands/fun/mapper.js
  commands/functions/osu/getServerAuthToken.js
  commands/functions/osu/getUserBeatmaps.js
  commands/functions/osu/getUserData.js
  commands/moderation/participant.js
  commands/moderation/purge.js
  commands/moderation/send.js
  commands/moderation/spectator.js
  config.example.json
  events/messageUpdate.js
  index.js
  package-lock.json
  package.json
  utils/parseDate.js
Labels: enhancement, large scope

#57 Implement cooldowns
  commands/index.ts
  commands/misc/help.ts
  commands/moderation/cooldown.ts
  commands/moderation/subcommands/cooldownClear.ts
  commands/moderation/subcommands/cooldownRemove.ts
  database/schemas/guild.ts
  package-lock.json
  package.json
  utils/core/commandHandler.ts
  utils/messages/checkCooldown.ts
Labels: enhancement, medium priority

#64 Logging channel
  commands/index.ts
  commands/management/cooldown.ts
  commands/management/logging.ts
  commands/management/quotes.ts
  commands/management/subcommands/cooldown/cooldownClear.ts
  commands/management/subcommands/cooldown/cooldownRemove.ts
  commands/management/subcommands/quotes/quotesAddWord.ts
  commands/management/subcommands/quotes/quotesGetList.ts
  commands/management/subcommands/quotes/quotesGetStatus.ts
  commands/management/subcommands/quotes/quotesSetCustom.ts
  commands/management/subcommands/quotes/quotesSetDefault.ts
  commands/management/subcommands/quotes/quotesSetList.ts
  commands/management/subcommands/quotes/quotesSetWord.ts
  commands/management/subcommands/quotes/quotesToggle.ts
  database/schemas/guild.ts
  events/guildMemberRemove.ts
  events/messageDelete.ts
  events/messageUpdate.ts
Labels: enhancement
