Repository Hiviexd/AxerBot, pull requests merged in 2022-09, with the labels that each got.

#193 colored mode icons, fix an unnoticed crash, some touchups
  commands/fun/coinflip.ts
  commands/fun/fact.ts
  commands/fun/pun.ts
  commands/fun/roll.ts
  commands/fun/yesno.ts
  helpers/interactions/registerCommands.ts
  helpers/text/generateColoredModeIcon.ts
  helpers/text/getEmoji.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
  responses/osu/BeatmapsetEmbed.ts
  responses/qat/BNEmbed.ts
Labels: size/L

#194 Add osumodhub request embeds
  database/schemas/guild.ts
  events/messageCreate.ts
  helpers/modhub/ModhubFetcher.ts
  helpers/modhub/fetcher/QueueFetcherManager.ts
  helpers/modhub/fetcher/RequestFetcherManager.ts
  helpers/modhub/url/checkModhubURL.ts
  helpers/modhub/url/processModhubURL.ts
  responses/modhub/RequestEmbed.ts
Labels: size/L

#195 minor polishing in openbns and modhub embeds
  commands/fun/revolver.ts
  commands/fun/yesno.ts
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
  helpers/qat/getters/requestStatus/getRequestStatus.ts
  responses/modhub/RequestEmbed.ts
  responses/qat/OpenBNsEmbed.ts
Labels: size/M

#196 display choices in /choose response
  commands/fun/choose.ts
Labels: size/XS

#197 Fix modhub embeds filter
  helpers/modhub/url/processModhubURL.ts
Labels: size/S

#198 add count to openbns embed
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
  helpers/text/numberToEmoji.ts
  responses/qat/OpenBNsEmbed.ts
Labels: size/M

#200 force bot to ignore threads
  events/messageCreate.ts
  package.json
  responses/text/yesno.txt
  yarn.lock
Labels: size/S

#201 support blacklisting BNs from tracking
  modules/tracking/qatTracking.ts
Labels: size/XS

#202 opt out more BNs from tracking
  modules/tracking/qatTracking.ts
Labels: size/XS

#203 rehaul /sendmessage and add /editmessage
  commands/index.ts
  commands/management/editMessage.ts
  commands/management/send.ts
  commands/management/sendMessage.ts
Labels: size/L

#204 remove message from form placeholder
  commands/management/editMessage.ts
Labels: size/XS

#205 convert reminder to embed
  commands/misc/reminder.ts
  modules/reminders/remindersChecker.ts
Labels: size/M
