Repository Hiviexd/AxerBot, pull requests merged in 2022-07, with the labels that each got.

#137 Add modes to verification system
  commands/management/subcommands/verification/setGroupRoles.ts
  commands/management/verification.ts
  database/utils/createNewUser.ts
  events/guildMemberAdd.ts
  events/guildMemberRemove.ts
Labels: size/L

#138 Add support to groups without modes
  commands/management/subcommands/verification/setGroupRoles.ts
  commands/management/verification.ts
Labels: size/M

#139 add roles to success embed
  commands/management/verification.ts
Labels: size/XS

#140 add usergroup icons to `openbns`
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
Labels: size/S

#142 Fix incorrect function
  helpers/core/commandHandler.ts
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
Labels: size/S

#143 Fix embed
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
Labels: size/S

#144 Async
  commands/BNsite/bn.ts
  commands/BNsite/openbns.ts
  commands/misc/avatar.ts
  commands/misc/invite.ts
  commands/misc/ping.ts
  events/interactionCreate.ts
  responses/osu/PlayerEmbed.ts
Labels: size/S

#145 fix verification interaction
  events/interactionCreate.ts
Labels: size/XS

#146 SHUT UP HIVIE
  commands/misc/help.ts
Labels: size/XS

#147 eae
  commands/fun/heardle.ts
  commands/index.ts
  commands/misc/avatar.ts
  commands/misc/help.ts
  commands/misc/reminder.ts
  database/schemas/user.ts
  helpers/core/commandHandler.ts
  helpers/general/relativeTime.ts
  package.json
  yarn.lock
Labels: size/XL

#148 fuck discord
  commands/fun/heardle.ts
Labels: size/XS

#149 heardle v2
  commands/fun/heardle.ts
  database/index.ts
  database/schemas/heardle.ts
  database/schemas/user.ts
  events/interactionCreate.ts
  helpers/osu/fetcher/startConnection.ts
  modules/heardle/heardle.ts
Labels: size/XL

#151 Fix bugs
  commands/management/cooldown.ts
  modules/heardle/heardle.ts
Labels: size/S

#152 Fix more bugs
  commands/user/mapsetrank.ts
  commands/user/osuset.ts
Labels: size/XS

#155 Migrate verification system to slash commands
  commands/dev/eval.ts
  commands/fun/choose.ts
  commands/fun/coinflip.ts
  commands/fun/fact.ts
  commands/fun/owoify.ts
  commands/fun/pun.ts
  commands/fun/revolver.ts
  commands/fun/roll.ts
  commands/fun/yesno.ts
  commands/management/subcommands/verification/addGroupRole.ts
  commands/management/subcommands/verification/addRole.ts
  commands/management/subcommands/verification/disable.ts
  commands/management/subcommands/verification/enable.ts
  commands/management/subcommands/verification/removeGroupRole.ts
  commands/management/subcommands/verification/removeRole.ts
  commands/management/subcommands/verification/setChannel.ts
  commands/management/subcommands/verification/setFlags.ts
  commands/management/subcommands/verification/setGroupRoles.ts
  commands/management/subcommands/verification/setMessage.ts
  commands/management/subcommands/verification/setRoles.ts
  commands/management/verification.ts
  helpers/core/slashCommandHandler.ts
  helpers/interactions/registerCommands.ts
Labels: size/XXL

#156 Fix reminders dup
  events/ready.ts
  modules/reminders/remindersChecker.ts
Labels: size/S

#157 Fix reminders dup (again)
  events/ready.ts
  modules/reminders/remindersChecker.ts
Labels: size/S

#158 Fix crash on reminders
  modules/reminders/remindersChecker.ts
Labels: size/XS

#159 verification docs
  commands/README.md
  commands/management/subcommands/verification/addGroupRole.ts
  commands/management/subcommands/verification/addRole.ts
  commands/management/subcommands/verification/disable.ts
  commands/management/subcommands/verification/enable.ts
  commands/management/subcommands/verification/removeGroupRole.ts
  commands/management/subcommands/verification/removeRole.ts
  commands/management/subcommands/verification/setChannel.ts
  commands/management/subcommands/verification/setFlags.ts
  commands/management/subcommands/verification/setMessage.ts
  commands/management/verification.ts
Labels: size/M

#160 improve reliability of mod embeds
  events/interactionCreate.ts
  helpers/osu/fetcher/general/storeBeatmap.ts
  helpers/text/truncateString.ts
  modules/downloader/beatmapDownloader.ts
  modules/heardle/heardle.ts
  package.json
  responses/osu/BeatmapsetDiscussionEmbed.ts
  responses/osu/BeatmapsetEmbed.ts
  responses/osu/CommentEmbed.ts
  yarn.lock
Labels: size/L

#161 Fix some bugs
  helpers/osu/fetcher/general/storeBeatmap.ts
  helpers/osu/player/getHighestUsergroup.ts
  helpers/text/abreviation.ts
  modules/downloader/beatmapDownloader.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
  responses/osu/BeatmapsetEmbed.ts
  responses/qat/BNEmbed.ts
Labels: size/L

#162 Fix incorrect name on bn embed
  responses/qat/BNEmbed.ts
Labels: size/XS

#163 Add BN tracker
  cache/nominators.json
  commands/BNsite/subcommands/tracker/addTrack.ts
  commands/BNsite/subcommands/tracker/removeTrack.ts
  commands/BNsite/tracking.ts
  commands/index.ts
  database/index.ts
  database/schemas/guild.ts
  database/schemas/track.ts
  events/ready.ts
  helpers/qat/getters/preferences/getBNPreferences.ts
  helpers/qat/getters/requestStatus/getRequestStatus.ts
  modules/tracking/qatTracking.ts
Labels: size/XL

#164 add legal stuff
  legal/PrivacyPolicy.md
  legal/TermsOfService.md
Labels: size/L

#165 add modes to bntracker embeds
  commands/BNsite/tracking.ts
  helpers/qat/getters/preferences/getBNPreferences.ts
  helpers/text/embeds/generateErrorEmbed.ts
  helpers/text/embeds/generateSuccessEmbed.ts
  modules/tracking/qatTracking.ts
Labels: size/M

#168 i may be stupid
  legal/PrivacyPolicy.md
Labels: size/XS

#170 hello gm
  .gitignore
  cache/nominators.json
  commands/index.ts
  helpers/osu/performance/calculateFruitsBeatmap.ts
  helpers/osu/performance/calculateManiaBeatmap.ts
  helpers/osu/performance/calculateOsuBeatmap.ts
  helpers/osu/performance/calculateTaikoBeatmap.ts
  helpers/osu/player/generatePlayerRankChart.ts
  helpers/osu/player/getHighestUsergroup.ts
  helpers/osu/player/hexToRgb.ts
  helpers/text/embeds/getBeatmapEmbedFields.ts
  package.json
  responses/osu/PlayerEmbed.ts
  types/user.ts
  yarn.lock
Labels: size/XL

#171 generate a reduced chart for users without badge
  cache/nominators.json
  helpers/osu/player/generatePlayerRankChart.ts
Labels: size/XS

#172 ok i can't use a font
  fonts/Quicksand-Bold.ttf
  fonts/Quicksand-Light.ttf
  fonts/Quicksand-Medium.ttf
  fonts/Quicksand-Regular.ttf
  fonts/Quicksand-SemiBold.ttf
  helpers/osu/player/generatePlayerRankChart.ts
Labels: size/XS

#174 add style preferences to bn tracker embed
  helpers/qat/getters/preferences/getBNPreferences.ts
Labels: size/S

#175 Fix embeds permissions
  .gitignore
  commands/management/embeds.ts
Labels: size/S

#177 make download prompts ephemeral
  commands/BNsite/tracking.ts
  modules/downloader/beatmapDownloader.ts
Labels: size/XS

#178 limit args in modes in /bntrack
  commands/BNsite/subcommands/tracker/addTrack.ts
  responses/qat/BNEmbed.ts
Labels: size/L
