Repository Hiviexd/AxerBot, pull requests merged in 2022-12, with the labels that each got.

#223 add 1 second delay to welcome embed
  README.md
  commands/BNsite/bn.ts
  events/guildMemberAdd.ts
Labels: size/S

#224 Some general cleanups
  Procfile
  commands/BNsite/bn.ts
  commands/BNsite/tracking.ts
  commands/dev/serverlist.ts
  commands/fun/fact.ts
  commands/fun/pun.ts
  commands/management/logging.ts
  commands/management/subcommands/quotes/quotesGetStatus.ts
  commands/management/subcommands/userLog/add.ts
  commands/management/userLog.ts
  commands/management/verification.ts
  commands/misc/avatar.ts
  commands/misc/help.ts
  commands/misc/reminder.ts
  commands/user/mapper.ts
  commands/user/mapsetrank.ts
  commands/user/player.ts
  commands/user/recent.ts
  constants/colors.ts
  helpers/core/sendCommandHelp.ts
  helpers/interactions/sendVerificationLink.ts
  helpers/text/embeds/generateConfirmationEmbed.ts
  helpers/text/embeds/generateErrorEmbed.ts
  helpers/text/embeds/generateMissingPermsEmbed.ts
  helpers/text/embeds/generateSuccessEmbed.ts
  modules/heardle/heardle.ts
  modules/loggers/logMessageDelete.ts
  modules/loggers/logMessageEdit.ts
  modules/loggers/logServerJoins.ts
  modules/loggers/logServerLeaves.ts
  modules/reminders/remindersChecker.ts
  modules/tracking/qatTracking.ts
  modules/verification/client/StartVerification.ts
  package.json
  patches/node-osu+2.2.1.patch
  responses/embeds/CommandNotFound.ts
  responses/embeds/CommandOptionInvalid.ts
  responses/embeds/MissingPermissions.ts
  responses/embeds/Processing.ts
  responses/embeds/UserNotFound.ts
  responses/embeds/UserNotMapper.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
  responses/osu/BeatmapsetEmbed.ts
  responses/osu/CommentEmbed.ts
  responses/osu/RecentScoreEmbed.ts
  responses/qat/OpenBNsEmbed.ts
  responses/qat/UserNotBNorNAT.ts
  tsconfig.json
  yarn.lock
Labels: size/XL

#225 Add rank roles
  commands/management/subcommands/verification/addRankRole.ts
  commands/management/subcommands/verification/removeRankRole.ts
  commands/management/verification.ts
  package.json
  yarn.lock
Labels: size/XL

#226 Fix possible undefined
  commands/management/verification.ts
Labels: size/XS

#227 fix crash when bn opens queue with invalid link
  helpers/qat/fetcher/qatUserActivity.ts
  modules/tracking/qatTracking.ts
Labels: size/XS

#229 add .env.example
  .env.example
  README.md
Labels: size/M

#230 Rewrite help command
  .envexample
  .gitignore
  cache/nominators.json
  commands/BNsite/bn.ts
  commands/BNsite/openbns.ts
  commands/contests/participant.ts
  commands/contests/resetRoles.ts
  commands/contests/spectator.ts
  commands/dev/eval.ts
  commands/dev/repeat.ts
  commands/dev/serverlist.ts
  commands/fun/choose.ts
  commands/fun/coinflip.ts
  commands/fun/fact.ts
  commands/fun/guessbg.ts
  commands/fun/heardle.ts
  commands/fun/owoify.ts
  commands/fun/pun.ts
  commands/fun/revolver.ts
  commands/fun/roll.ts
  commands/fun/yesno.ts
  commands/index.ts
  commands/management/cooldown.ts
  commands/management/embeds.ts
  commands/management/logging.ts
  commands/management/purge.ts
  commands/management/quotes.ts
  commands/management/setprefix.ts
  commands/management/subcommands/cooldown/cooldownClear.ts
  commands/management/subcommands/cooldown/cooldownRemove.ts
  commands/management/subcommands/quotes/quotesAddWord.ts
  commands/management/subcommands/quotes/quotesAllowChannels.ts
  commands/management/subcommands/quotes/quotesBlockChannels.ts
  commands/management/subcommands/quotes/quotesGetList.ts
  commands/management/subcommands/quotes/quotesGetStatus.ts
  commands/management/subcommands/quotes/quotesSetChance.ts
  commands/management/subcommands/quotes/quotesSetCustom.ts
  commands/management/subcommands/quotes/quotesSetDefault.ts
  commands/management/subcommands/quotes/quotesSetDisabled.ts
  commands/management/subcommands/quotes/quotesSetList.ts
  commands/management/subcommands/quotes/quotesSetWord.ts
  commands/management/subcommands/verification/setMessage.ts
  commands/management/userLog.ts
  commands/misc/avatar.ts
  commands/misc/help.ts
  commands/misc/invite.ts
  commands/misc/ping.ts
  commands/misc/reminder.ts
  commands/user/mapper.ts
  commands/user/mapsetrank.ts
  commands/user/osuset.ts
  commands/user/player.ts
  commands/user/recent.ts
  helpers/core/commandHandler.ts
  helpers/core/slashCommandHandler.ts
  helpers/interactions/registerCommands.ts
  yarn-error.log
Labels: size/XXL

#231 bruh momento
  commands/misc/help.ts
Labels: size/XS

#232 Add general help again
  commands/misc/help.ts
Labels: size/M

#233 Improve recent embed
  commands/user/recent.ts
  helpers/osu/performance/calculateBeatmap.ts
  helpers/osu/performance/calculateScore.ts
  responses/osu/RecentScoreEmbed.ts
Labels: size/XL

#234 Fix rs metadata
  commands/index.ts
  commands/user/recent.ts
Labels: size/XS
