Repository Hiviexd/AxerBot, pull requests merged in 2022-06, with the labels that each got.

#115 stuff
  commands/fun/fact.ts
  helpers/general/sendQuotes.ts
Labels: size/XS

#116 Add `reminder` command
  commands/index.ts
  commands/misc/reminder.ts
  database/schemas/user.ts
  events/ready.ts
  helpers/reminder/remindersChecker.ts
Labels: enhancement, size/L

#120 attempt to fix reminders
  helpers/reminder/remindersChecker.ts
Labels: size/M

#121 🧹
  commands/management/subcommands/verification/setMessage.ts
  commands/management/verification.ts
  database/schemas/guild.ts
  events/ready.ts
  helpers/interactions/sendVerificationLink.ts
  modules/reminders/remindersChecker.ts
  modules/verification/client/StartVerification.ts
Labels: size/S

#123 BNsite integration + add `bn` command
  commands/BNsite/bn.ts
  commands/index.ts
  commands/misc/help.ts
  commands/misc/ping.ts
  commands/user/mapper.ts
  commands/user/mapsetrank.ts
  commands/user/player.ts
  commands/user/recent.ts
  helpers/qat/fetcher/qatApi.ts
  helpers/qat/fetcher/qatUser.ts
  helpers/qat/fetcher/qatUserActivity.ts
  helpers/qat/getters/genres/getGenres.ts
  helpers/qat/getters/genres/getTop3Genres.ts
  helpers/qat/getters/languages/getLanguages.ts
  helpers/qat/getters/languages/getTop3Languages.ts
  helpers/qat/getters/mappers/getMappers.ts
  helpers/qat/getters/mappers/getTop3Mappers.ts
  helpers/qat/getters/mappers/getUniqueMappersNumber.ts
  helpers/qat/getters/requestStatus/getRequestStatus.ts
  helpers/text/calculateDuration.ts
  responses/qat/BNEmbed.ts
  responses/qat/UserNotBNorNAT.ts
  types/qat.ts
Labels: enhancement, size/XL

#124 bugfix speedrun
  commands/management/cooldown.ts
Labels: size/XS

#125 im losing my mind
  database/schemas/guild.ts
Labels: size/XS

#126 please work
  database/migrations/addBNsiteToCooldown.ts
Labels: size/S

#127 sdfgopuiyhgosdfg
  database/index.ts
Labels: size/XS

#128 TYPOOOOOOO
  database/migrations/addBNsiteToCooldown.ts
Labels: size/XS

#129 remove migration
  database/index.ts
  database/migrations/addBNsiteToCooldown.ts
Labels: size/XS

#130 🧹
  helpers/general/sendQuotes.ts
  responses/qat/BNEmbed.ts
Labels: size/M

#131 fix role id input
  commands/management/subcommands/verification/setRoles.ts
Labels: size/S

#132 documentation
  README.md
  commands/BNsite/bn.ts
  commands/README.md
  commands/index.ts
  commands/misc/invite.ts
  config.example.json
  helpers/text/embeds/generateErrorEmbed.ts
Labels: documentation, size/L

#133 oops
  commands/BNsite/bn.ts
  commands/index.ts
Labels: size/XS

#135 Add `openbns` command
  commands/BNsite/openbns.ts
  commands/index.ts
  commands/misc/reminder.ts
  helpers/osu/player/getHighestUsergroup.ts
  helpers/qat/fetcher/qatAllUsers.ts
  helpers/qat/fetcher/qatApi.ts
  helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
  helpers/qat/getters/requestStatus/getRequestStatus.ts
  responses/qat/BNEmbed.ts
  responses/qat/OpenBNsEmbed.ts
  types/qat.ts
Labels: size/L

#136 attempt to fix duplicate reminders
  commands/misc/reminder.ts
  events/ready.ts
Labels: size/S
