Repository Hiviexd/AxerBot, pull requests merged in 2022-08, with the labels that each got.

#179 attempt at fixing bug that deletes bntrackers
  modules/tracking/qatTracking.ts
Labels: size/XS

#180 Refactor logging system
  events/guildMemberAdd.ts
  events/guildMemberRemove.ts
  events/messageDelete.ts
  events/messageUpdate.ts
  helpers/general/sendQuotes.ts
  modules/loggers/logMessageDelete.ts
  modules/loggers/logMessageEdit.ts
  modules/loggers/logServerJoins.ts
  modules/loggers/logServerLeaves.ts
Labels: size/L

#181 BRO
  modules/tracking/qatTracking.ts
Labels: size/XS

#182 watching
  modules/serverCount/serverCountInStatus.ts
Labels: size/XS

#183 Remove duplicated word
  README.md
Labels: size/XS

#184 Fix discussion embed and add post location
  helpers/osu/url/checkOsuURL.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
Labels: size/S

#186 handle error case where bot lacks perm to send msg
  events/messageCreate.ts
Labels: size/S

#187 add touchups to presence
  events/ready.ts
  modules/presence/presence.ts
  modules/serverCount/serverCountInStatus.ts
Labels: size/M

#188 Add preview button to verification setmessage
  cache/nominators.json
  commands/management/subcommands/verification/setMessage.ts
  events/interactionCreate.ts
  modules/verification/message/previewVerificationMessage.ts
Labels: size/M

#189 Add cache to gitignore
  .gitignore
Labels: size/XS

#192 improve reminder error
  commands/misc/reminder.ts
Labels: size/XS
