Repository Hiviexd/AxerBot, pull requests merged in 2023-02, with the labels that each got.

#242 temporarily disable verification
  .prettierrc
  modules/verification/client/StartVerification.ts
Labels: size/L

#243 explain more
  modules/verification/client/StartVerification.ts
Labels: size/XS

#244 Implement updates
  database/index.ts
  database/schemas/verification.ts
  events/messageCreate.ts
  helpers/interactions/sendVerificationLink.ts
  index.ts
  modules/bancho/client.ts
  modules/bancho/commands/index.ts
  modules/bancho/commands/verify.ts
  modules/loggers/logMessageDelete.ts
  modules/loggers/logMessageEdit.ts
  modules/loggers/logServerJoins.ts
  modules/loggers/logServerLeaves.ts
  modules/tracking/qatTracking.ts
  modules/verification/client/GenerateAuthToken.ts
  modules/verification/client/StartVerification.ts
  modules/verification/client/validateVerificationRequirements.ts
  package.json
  responses/osu/BeatmapsetEmbed.ts
  responses/verification/sendLoggerEmbed.ts
  responses/verification/sendVerifiedEmbed.ts
  types/user.ts
  yarn.lock
Labels: size/XXL

#246 add daily avatars
  .gitignore
  avatars/1.jpg
  avatars/10.jpg
  avatars/11.jpg
  avatars/12.jpg
  avatars/13.jpg
  avatars/14.jpg
  avatars/15.jpg
  avatars/16.jpg
  avatars/17.jpg
  avatars/18.jpg
  avatars/19.jpg
  avatars/2.jpg
  avatars/20.jpg
  avatars/21.jpg
  avatars/22.jpg
  avatars/23.jpg
  avatars/24.jpg
  avatars/3.jpg
  avatars/4.jpg
  avatars/5.jpg
  avatars/6.jpg
  avatars/7.jpg
  avatars/8.jpg
  avatars/9.jpg
  index.ts
  modules/avatar/avatarManager.ts
  responses/text/quotes.txt
  responses/text/yesno.txt
Labels: size/L

#247 Fix verification system not working
  commands/management/subcommands/verification/addGroupRole.ts
  commands/management/subcommands/verification/addRankRole.ts
  commands/management/subcommands/verification/addRole.ts
  commands/management/subcommands/verification/disable.ts
  commands/management/subcommands/verification/enable.ts
  commands/management/subcommands/verification/removeGroupRole.ts
  commands/management/subcommands/verification/removeRankRole.ts
  commands/management/subcommands/verification/removeRole.ts
  commands/management/subcommands/verification/setButton.ts
  commands/management/subcommands/verification/setChannel.ts
  commands/management/subcommands/verification/setFlags.ts
  commands/management/subcommands/verification/setMessage.ts
  commands/management/subcommands/verification/status.ts
  helpers/interactions/sendVerificationLink.ts
  modules/avatar/avatarManager.ts
  modules/verification/client/StartVerification.ts
Labels: size/L

#248 general cleanups
  .env.example
  .gitignore
  README.md
  commands/general/about.ts
  commands/general/avatar.ts
  commands/general/help.ts
  commands/general/ping.ts
  commands/general/reminder.ts
  commands/general/subcommands/reminder/createReminder.ts
  commands/general/subcommands/reminder/listReminders.ts
  commands/general/subcommands/reminder/removeReminder.ts
  commands/index.ts
  commands/osu/mapper.ts
  commands/osu/mappertracker.ts
  commands/osu/mapsetrank.ts
  commands/osu/osuset.ts
  commands/osu/player.ts
  commands/osu/recent.ts
  commands/osu/subcommands/listTracker.ts
  commands/osu/subcommands/newTracker.ts
  commands/osu/subcommands/removeTracker.ts
  index.ts
  models/commands/SlashCommand.ts
  modules/mappertracker/mapperTrackerManager.ts
Labels: size/L

#249 cleanup mapper tracker embeds
  responses/mappertracker/SendBeatmapDisqualifyEmbed.ts
  responses/mappertracker/SendBeatmapFavoriteEmbed.ts
  responses/mappertracker/SendBeatmapGraveyardEmbed.ts
  responses/mappertracker/SendBeatmapHypeEmbed.ts
  responses/mappertracker/SendBeatmapLovedEmbed.ts
  responses/mappertracker/SendBeatmapNominationEmbed.ts
  responses/mappertracker/SendBeatmapNominationResetEmbed.ts
  responses/mappertracker/SendBeatmapQualifyEmbed.ts
  responses/mappertracker/SendBeatmapRankedEmbed.ts
  responses/mappertracker/SendBeatmapReviveEmbed.ts
  responses/mappertracker/SendNewBeatmapEmbed.ts
Labels: size/M

#250 better wording in verify embed
  helpers/interactions/sendVerificationLink.ts
Labels: size/XS

#251 General cleanups and fixes
  .gitignore
  commands/BNsite/bn.ts
  commands/BNsite/bntracker.ts
  commands/BNsite/openbns.ts
  commands/fun/choose.ts
  commands/general/ping.ts
  commands/general/reminder.ts
  commands/index.ts
  commands/management/editMessage.ts
  commands/management/sendMessage.ts
  commands/management/subcommands/verification/setMessage.ts
  commands/tools/resizebg.ts
  commands/tools/spectro.ts
  index.ts
  modules/bancho/client.ts
Labels: size/M

#252 wording
  commands/tools/debloat.ts
  commands/tools/spectro.ts
Labels: size/M

#253 add /setroles command
  commands/index.ts
  commands/management/setRoles.ts
  commands/management/subcommands/setRoles/setRolesAddPreset.ts
  commands/management/subcommands/setRoles/setRolesApply.ts
  commands/management/subcommands/setRoles/setRolesListPresets.ts
  commands/management/subcommands/setRoles/setRolesRemovePreset.ts
  commands/management/subcommands/userLog/addLog.ts
  commands/management/subcommands/userLog/list.ts
  commands/management/subcommands/userLog/remove.ts
  database/schemas/guild.ts
  helpers/text/parseOsuTimestamps.ts
  helpers/text/replaceOsuTimestampsToURL.ts
  responses/osu/BeatmapsetDiscussionEmbed.ts
Labels: feature, size/L

#254 add more info to preset apply embed
  commands/management/subcommands/setRoles/setRolesApply.ts
Labels: size/S

#255 add black diff icons
  helpers/text/generateColoredModeIcon.ts
  helpers/text/getEmoji.ts
Labels: size/S
